// GENERATED FILE — do not edit by hand.
// Regenerate: BUNDLED_GEN_WRITE=1 yarn test bundledModelSuggestions.gen
import {Classifier, Tier} from '../services/deviceRules/types';
import {ModelSuggestion} from '../services/suggestions/types';

type Platform = 'android' | 'ios';

interface BundledSnapshot {
  version: string;
  schemaVersion: string;
  classifiers: Record<Platform, Classifier>;
  tierSuggestions: Record<Platform, Record<Tier, ModelSuggestion[]>>;
}

export const bundledModelSuggestions: BundledSnapshot = {
  version: '2026-06-10.1+2026-06-10.1',
  schemaVersion: '1.1.0-draft',
  classifiers: {
    android: {
      ramBands: [
        {
          id: 'lt-4',
          maxBytes: 4294967296,
        },
        {
          id: '4-6',
          maxBytes: 6442450944,
        },
        {
          id: '6-8',
          maxBytes: 8589934592,
        },
        {
          id: '8-12',
          maxBytes: 12884901888,
        },
        {
          id: '12-plus',
          maxBytes: null,
        },
      ],
      tierMatrix: [
        {
          ramBand: 'lt-4',
          socClass: 'budget',
          tier: 'low',
        },
        {
          ramBand: 'lt-4',
          socClass: 'mid',
          tier: 'low',
        },
        {
          ramBand: 'lt-4',
          socClass: 'flagship',
          tier: 'low',
        },
        {
          ramBand: '4-6',
          socClass: 'budget',
          tier: 'low',
        },
        {
          ramBand: '4-6',
          socClass: 'mid',
          tier: 'low',
        },
        {
          ramBand: '4-6',
          socClass: 'flagship',
          tier: 'mid',
        },
        {
          ramBand: '6-8',
          socClass: 'budget',
          tier: 'low',
        },
        {
          ramBand: '6-8',
          socClass: 'mid',
          tier: 'mid',
        },
        {
          ramBand: '6-8',
          socClass: 'flagship',
          tier: 'high',
        },
        {
          ramBand: '8-12',
          socClass: 'budget',
          tier: 'mid',
        },
        {
          ramBand: '8-12',
          socClass: 'mid',
          tier: 'high',
        },
        {
          ramBand: '8-12',
          socClass: 'flagship',
          tier: 'flagship',
        },
        {
          ramBand: '12-plus',
          socClass: 'budget',
          tier: 'mid',
        },
        {
          ramBand: '12-plus',
          socClass: 'mid',
          tier: 'high',
        },
        {
          ramBand: '12-plus',
          socClass: 'flagship',
          tier: 'flagship',
        },
      ],
      socModelToClass: {
        SM8850: 'flagship',
        SM8750: 'flagship',
        SM8650: 'flagship',
        SM8635: 'flagship',
        SM8550: 'flagship',
        SM8475: 'flagship',
        SM8450: 'flagship',
        SM8350: 'flagship',
        SM8250: 'flagship',
        SM8150: 'flagship',
        'SM7475-AB': 'mid',
        SM7435: 'mid',
        SM7325: 'mid',
        SM7250: 'mid',
        SM7225: 'mid',
        SM6450: 'budget',
        SM6375: 'budget',
        SM6225: 'budget',
        SM4350: 'budget',
        MT6993: 'flagship',
        MT6991: 'flagship',
        MT6989: 'flagship',
        MT6985: 'flagship',
        MT6983: 'flagship',
        MT6896: 'flagship',
        MT6886: 'flagship',
        MT6877: 'mid',
        MT6875: 'mid',
        MT6855: 'mid',
        MT6853: 'budget',
        MT6833: 'budget',
        MT6789: 'budget',
        MT6769: 'budget',
        s5e9945: 'flagship',
        s5e9935: 'flagship',
        s5e9925: 'flagship',
        s5e9855: 'mid',
        s5e8855: 'mid',
        s5e8845: 'mid',
        s5e8835: 'mid',
        s5e8825: 'mid',
        Tensor: 'mid',
        'Tensor G2': 'mid',
        'Tensor G3': 'mid',
        'Tensor G4': 'mid',
        'Tensor G5': 'mid',
      },
      hardwareToClass: {
        sun: 'flagship',
        pineapple: 'flagship',
        kalama: 'flagship',
        taro: 'flagship',
        lahaina: 'flagship',
        kona: 'flagship',
        msmnile: 'flagship',
        sdm845: 'mid',
        tokay: 'mid',
        shiba: 'mid',
        komodo: 'mid',
        caiman: 'mid',
        akita: 'mid',
        mustang: 'mid',
        blazer: 'mid',
        husky: 'mid',
        s5e9945: 'flagship',
        s5e9925: 'flagship',
        exynos2100: 'flagship',
        exynos990: 'flagship',
        k6991v1_64: 'flagship',
        k6989v1_64: 'flagship',
        k6993v1_64: 'flagship',
        houji: 'flagship',
        duchamp: 'flagship',
        rothko: 'flagship',
        canoe: 'flagship',
        rodin: 'flagship',
        peridot: 'flagship',
        zircon: 'flagship',
        crow: 'flagship',
        holi: 'mid',
        lito: 'mid',
        oriole: 'mid',
        cheetah: 'mid',
        bluejay: 'mid',
        panther: 'mid',
        lynx: 'mid',
        raven: 'mid',
        barbet: 'mid',
        tegu: 'mid',
        s5e8835: 'mid',
        s5e8855: 'mid',
        s5e8845: 'mid',
        s5e8825: 'mid',
        a34x: 'mid',
        marble: 'mid',
        garnet: 'mid',
        vayu: 'mid',
        sweet: 'mid',
        pipa: 'mid',
        Spacewar: 'mid',
        volcano: 'mid',
        parrot: 'mid',
        cancunf: 'mid',
        bangkk: 'mid',
        bengal: 'budget',
        a32: 'budget',
        a15: 'budget',
        rosemary: 'budget',
      },
      cpuHeuristic: [
        {
          match: {
            featuresAny: ['i8mm'],
          },
          class: 'flagship',
        },
        {
          match: {
            featuresAny: ['sve2'],
          },
          class: 'flagship',
        },
        {
          match: {
            maxFreqMhzMin: 3000,
          },
          class: 'flagship',
        },
        {
          match: {
            featuresAll: ['dotprod'],
            maxFreqMhzMin: 2400,
          },
          class: 'mid',
        },
        {
          match: {
            featuresAll: ['dotprod'],
          },
          class: 'mid',
        },
        {
          match: {},
          class: 'budget',
        },
      ],
    },
    ios: {
      ramBands: [
        {
          id: 'lt-3',
          maxBytes: 3221225472,
        },
        {
          id: '3-4',
          maxBytes: 4294967296,
        },
        {
          id: '4-6',
          maxBytes: 6442450944,
        },
        {
          id: '6-8',
          maxBytes: 8589934592,
        },
        {
          id: '8-plus',
          maxBytes: null,
        },
      ],
      tierMatrix: [
        {
          ramBand: 'lt-3',
          socClass: 'entry',
          tier: 'low',
        },
        {
          ramBand: 'lt-3',
          socClass: 'mid',
          tier: 'low',
        },
        {
          ramBand: 'lt-3',
          socClass: 'flagship',
          tier: 'low',
        },
        {
          ramBand: '3-4',
          socClass: 'entry',
          tier: 'low',
        },
        {
          ramBand: '3-4',
          socClass: 'mid',
          tier: 'low',
        },
        {
          ramBand: '3-4',
          socClass: 'flagship',
          tier: 'mid',
        },
        {
          ramBand: '4-6',
          socClass: 'entry',
          tier: 'low',
        },
        {
          ramBand: '4-6',
          socClass: 'mid',
          tier: 'mid',
        },
        {
          ramBand: '4-6',
          socClass: 'flagship',
          tier: 'high',
        },
        {
          ramBand: '6-8',
          socClass: 'entry',
          tier: 'mid',
        },
        {
          ramBand: '6-8',
          socClass: 'mid',
          tier: 'high',
        },
        {
          ramBand: '6-8',
          socClass: 'flagship',
          tier: 'high',
        },
        {
          ramBand: '8-plus',
          socClass: 'entry',
          tier: 'mid',
        },
        {
          ramBand: '8-plus',
          socClass: 'mid',
          tier: 'high',
        },
        {
          ramBand: '8-plus',
          socClass: 'flagship',
          tier: 'flagship',
        },
      ],
      deviceIdToChip: {
        'iPhone10,1': 'A11',
        'iPhone10,2': 'A11',
        'iPhone10,3': 'A11',
        'iPhone10,4': 'A11',
        'iPhone10,5': 'A11',
        'iPhone10,6': 'A11',
        'iPhone11,2': 'A12',
        'iPhone11,4': 'A12',
        'iPhone11,6': 'A12',
        'iPhone11,8': 'A12',
        'iPhone12,1': 'A13',
        'iPhone12,3': 'A13',
        'iPhone12,5': 'A13',
        'iPhone12,8': 'A13',
        'iPhone13,1': 'A14',
        'iPhone13,2': 'A14',
        'iPhone13,3': 'A14',
        'iPhone13,4': 'A14',
        'iPhone14,2': 'A15',
        'iPhone14,3': 'A15',
        'iPhone14,4': 'A15',
        'iPhone14,5': 'A15',
        'iPhone14,6': 'A15',
        'iPhone14,7': 'A15',
        'iPhone14,8': 'A15',
        'iPhone15,2': 'A16',
        'iPhone15,3': 'A16',
        'iPhone15,4': 'A16',
        'iPhone15,5': 'A16',
        'iPhone16,1': 'A17 Pro',
        'iPhone16,2': 'A17 Pro',
        'iPhone17,1': 'A18 Pro',
        'iPhone17,2': 'A18 Pro',
        'iPhone17,3': 'A18',
        'iPhone17,4': 'A18',
        'iPhone17,5': 'A18',
        'iPhone18,1': 'A19 Pro',
        'iPhone18,2': 'A19 Pro',
        'iPhone18,3': 'A19',
        'iPhone18,4': 'A19',
        'iPad7,11': 'A10',
        'iPad7,12': 'A10',
        'iPad11,1': 'A12',
        'iPad11,2': 'A12',
        'iPad11,3': 'A12',
        'iPad11,4': 'A12',
        'iPad11,6': 'A13',
        'iPad11,7': 'A13',
        'iPad12,1': 'A13',
        'iPad12,2': 'A13',
        'iPad13,1': 'A14',
        'iPad13,2': 'A14',
        'iPad13,4': 'M1',
        'iPad13,5': 'M1',
        'iPad13,6': 'M1',
        'iPad13,7': 'M1',
        'iPad13,8': 'M1',
        'iPad13,9': 'M1',
        'iPad13,10': 'M1',
        'iPad13,11': 'M1',
        'iPad13,16': 'M1',
        'iPad13,17': 'M1',
        'iPad13,18': 'A14',
        'iPad13,19': 'A14',
        'iPad14,1': 'A15',
        'iPad14,2': 'A15',
        'iPad14,3': 'M2',
        'iPad14,4': 'M2',
        'iPad14,5': 'M2',
        'iPad14,6': 'M2',
        'iPad14,8': 'M2',
        'iPad14,9': 'M2',
        'iPad14,10': 'M2',
        'iPad14,11': 'M2',
        'iPad15,3': 'M3',
        'iPad15,4': 'M3',
        'iPad15,5': 'M3',
        'iPad15,6': 'M3',
        'iPad15,7': 'A16',
        'iPad15,8': 'A16',
        'iPad16,1': 'A17 Pro',
        'iPad16,2': 'A17 Pro',
        'iPad16,3': 'M4',
        'iPad16,4': 'M4',
        'iPad16,5': 'M4',
        'iPad16,6': 'M4',
        'iPad17,1': 'M5',
        'iPad17,2': 'M5',
        'iPad17,3': 'M5',
        'iPad17,4': 'M5',
      },
      chipToClass: {
        A10: 'entry',
        A11: 'entry',
        A12: 'entry',
        A12X: 'entry',
        A12Z: 'entry',
        A13: 'entry',
        A14: 'mid',
        A15: 'mid',
        A16: 'mid',
        A17: 'mid',
        'A17 Pro': 'flagship',
        A18: 'mid',
        'A18 Pro': 'flagship',
        A19: 'flagship',
        'A19 Pro': 'flagship',
        M1: 'flagship',
        M2: 'flagship',
        M3: 'flagship',
        M4: 'flagship',
        M5: 'flagship',
      },
      deviceFamilyFallback: [
        {
          match: {
            idPrefix: 'iPhone',
            idMajorMin: 18,
          },
          class: 'flagship',
        },
        {
          match: {
            idPrefix: 'iPhone',
            idMajorMin: 15,
          },
          class: 'mid',
        },
        {
          match: {
            idPrefix: 'iPad',
            idMajorMin: 16,
            minRamBytes: 8589934592,
          },
          class: 'flagship',
        },
        {
          match: {
            idPrefix: 'iPad',
          },
          class: 'mid',
        },
        {
          match: {},
          class: 'entry',
        },
      ],
    },
  },
  tierSuggestions: {
    android: {
      low: [
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 2,
          obsTg: 10.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-1.7B-gguf',
            hfFilename: 'Bonsai-1.7B-Q1_0.gguf',
          },
          displayName: 'bonsai-1.7b',
          quant: 'q1_0',
          sizeBytes: 248302272,
          params: 1720028160,
          minRamGb: 1.5,
          obsTg: 9.4,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/Qwen_Qwen3-0.6B-GGUF',
            hfFilename: 'Qwen_Qwen3-0.6B-Q4_K_M.gguf',
          },
          displayName: 'qwen3-0.6b',
          quant: 'q4_k_m',
          sizeBytes: 484220320,
          params: 751632384,
          minRamGb: 1.3,
          obsTg: 11.9,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-350M-GGUF',
            hfFilename: 'LFM2.5-350M-Q4_K_M.gguf',
          },
          displayName: 'lfm2.5-350m',
          quant: 'q4_k_m',
          sizeBytes: 229312224,
          params: 354483968,
          minRamGb: 1.2,
          obsTg: 39.1,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      mid: [
        {
          key: {
            hfRepo: 'bartowski/HuggingFaceTB_SmolLM3-3B-GGUF',
            hfFilename: 'HuggingFaceTB_SmolLM3-3B-Q4_0.gguf',
          },
          displayName: 'smollm3-3b',
          quant: 'q4_0',
          sizeBytes: 1811455808,
          params: 3075098624,
          minRamGb: 3.1,
          obsTg: 8.9,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2-2.6B-GGUF',
            hfFilename: 'LFM2-2.6B-Q4_K_M.gguf',
          },
          displayName: 'lfm2-2.6b',
          quant: 'q4_k_m',
          sizeBytes: 1563668704,
          params: 2569272320,
          minRamGb: 2.5,
          obsTg: 12.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/Qwen_Qwen3-1.7B-GGUF',
            hfFilename: 'Qwen_Qwen3-1.7B-Q4_K_M.gguf',
          },
          displayName: 'qwen3-1.7b',
          quant: 'q4_k_m',
          sizeBytes: 1282439584,
          params: 2031739904,
          minRamGb: 2.1,
          obsTg: 8.5,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF',
            hfFilename: 'LFM2.5-1.2B-Instruct-Q4_K_M.gguf',
          },
          displayName: 'lfm2.5-1.2b',
          quant: 'q4_k_m',
          sizeBytes: 730895168,
          params: 1170340608,
          minRamGb: 1.4,
          obsTg: 21.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-8B-gguf',
            hfFilename: 'Bonsai-8B-Q1_0.gguf',
          },
          displayName: 'bonsai-8b',
          quant: 'q1_0',
          sizeBytes: 1158654496,
          params: 8188548096,
          minRamGb: 2.3,
          obsTg: 3.6,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 2,
          obsTg: 11.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      high: [
        {
          key: {
            hfRepo: 'unsloth/gemma-3-4b-it-GGUF',
            hfFilename: 'gemma-3-4b-it-Q4_0.gguf',
          },
          displayName: 'gemma-3-4b',
          quant: 'q4_0',
          sizeBytes: 2370065536,
          params: 3880263168,
          minRamGb: 4.5,
          obsTg: 6.6,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/gemma-4-E2B-it-GGUF',
            hfFilename: 'gemma-4-E2B-it-Q4_0.gguf',
          },
          displayName: 'gemma-4-e2b',
          quant: 'q4_0',
          sizeBytes: 3041376384,
          params: 4647450147,
          minRamGb: 4.5,
          obsTg: 7.2,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-8B-gguf',
            hfFilename: 'Bonsai-8B-Q1_0.gguf',
          },
          displayName: 'bonsai-8b',
          quant: 'q1_0',
          sizeBytes: 1158654496,
          params: 8188548096,
          minRamGb: 2.3,
          obsTg: 3.6,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/microsoft_Phi-4-mini-instruct-GGUF',
            hfFilename: 'microsoft_Phi-4-mini-instruct-Q4_0.gguf',
          },
          displayName: 'phi-4-mini-instruct',
          quant: 'q4_0',
          sizeBytes: 2331442560,
          params: 3836021856,
          minRamGb: 4.1,
          obsTg: 6.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-4B-gguf',
            hfFilename: 'Bonsai-4B-Q1_0.gguf',
          },
          displayName: 'bonsai-4b',
          quant: 'q1_0',
          sizeBytes: 572270624,
          params: 4021784576,
          minRamGb: 1.6,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 2,
          obsTg: 14.1,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      flagship: [
        {
          key: {
            hfRepo: 'unsloth/gemma-3-4b-it-GGUF',
            hfFilename: 'gemma-3-4b-it-Q4_0.gguf',
          },
          displayName: 'gemma-3-4b',
          quant: 'q4_0',
          sizeBytes: 2370065536,
          params: 3880263168,
          minRamGb: 4.5,
          obsTg: 7.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/gemma-4-E4B-it-GGUF',
            hfFilename: 'gemma-4-E4B-it-Q4_0.gguf',
          },
          displayName: 'gemma-4-e4b',
          quant: 'q4_0',
          sizeBytes: 4836000928,
          params: 7518069290,
          minRamGb: 7.9,
          obsTg: 6.5,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/gemma-4-E2B-it-GGUF',
            hfFilename: 'gemma-4-E2B-it-Q4_0.gguf',
          },
          displayName: 'gemma-4-e2b',
          quant: 'q4_0',
          sizeBytes: 3041376384,
          params: 4647450147,
          minRamGb: 4.5,
          obsTg: 9,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-8B-A1B-GGUF',
            hfFilename: 'LFM2.5-8B-A1B-Q4_0.gguf',
          },
          displayName: 'lfm2.5-8b-a1b',
          quant: 'q4_0',
          sizeBytes: 4844678368,
          params: 8467856832,
          minRamGb: 6.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/mistralai_Ministral-3-3B-Instruct-2512-GGUF',
            hfFilename: 'mistralai_Ministral-3-3B-Instruct-2512-Q4_0.gguf',
          },
          displayName: 'ministral-3-3b',
          quant: 'q4_0',
          sizeBytes: 2046375904,
          params: 3429006336,
          minRamGb: 3.7,
          obsTg: 5.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 2,
          obsTg: 23.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
    },
    ios: {
      low: [
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 1.8,
          obsTg: 30,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-1.7B-gguf',
            hfFilename: 'Bonsai-1.7B-Q1_0.gguf',
          },
          displayName: 'bonsai-1.7b',
          quant: 'q1_0',
          sizeBytes: 248302272,
          params: 1720028160,
          minRamGb: 1.3,
          obsTg: 51.2,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/Qwen_Qwen3-0.6B-GGUF',
            hfFilename: 'Qwen_Qwen3-0.6B-Q4_K_M.gguf',
          },
          displayName: 'qwen3-0.6b',
          quant: 'q4_k_m',
          sizeBytes: 484220320,
          params: 751632384,
          minRamGb: 1.2,
          obsTg: 49.3,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-350M-GGUF',
            hfFilename: 'LFM2.5-350M-Q4_K_M.gguf',
          },
          displayName: 'lfm2.5-350m',
          quant: 'q4_k_m',
          sizeBytes: 229312224,
          params: 354483968,
          minRamGb: 1.1,
          obsTg: 88.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      mid: [
        {
          key: {
            hfRepo: 'bartowski/HuggingFaceTB_SmolLM3-3B-GGUF',
            hfFilename: 'HuggingFaceTB_SmolLM3-3B-Q4_K_M.gguf',
          },
          displayName: 'smollm3-3b',
          quant: 'q4_k_m',
          sizeBytes: 1915305792,
          params: 3075098624,
          minRamGb: 2.8,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2-2.6B-GGUF',
            hfFilename: 'LFM2-2.6B-Q4_K_M.gguf',
          },
          displayName: 'lfm2-2.6b',
          quant: 'q4_k_m',
          sizeBytes: 1563668704,
          params: 2569272320,
          minRamGb: 2.3,
          obsTg: 25.4,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/Qwen_Qwen3-1.7B-GGUF',
            hfFilename: 'Qwen_Qwen3-1.7B-Q4_K_M.gguf',
          },
          displayName: 'qwen3-1.7b',
          quant: 'q4_k_m',
          sizeBytes: 1282439584,
          params: 2031739904,
          minRamGb: 2,
          obsTg: 23.8,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF',
            hfFilename: 'LFM2.5-1.2B-Instruct-Q4_K_M.gguf',
          },
          displayName: 'lfm2.5-1.2b',
          quant: 'q4_k_m',
          sizeBytes: 730895168,
          params: 1170340608,
          minRamGb: 1.3,
          obsTg: 54.9,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/Qwen3.5-2B-GGUF',
            hfFilename: 'Qwen3.5-2B-Q4_K_M.gguf',
          },
          displayName: 'qwen3.5-2b',
          quant: 'q4_k_m',
          sizeBytes: 1280835840,
          params: 1881825088,
          minRamGb: 2.4,
          obsTg: 18.8,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 1.8,
          obsTg: 36.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      high: [
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-4b-it-GGUF',
            hfFilename: 'gemma-3-4b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-4b',
          quant: 'q4_k_m',
          sizeBytes: 2489757856,
          params: 3880099328,
          minRamGb: 4.1,
          obsTg: 11.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/gemma-4-E2B-it-GGUF',
            hfFilename: 'gemma-4-E2B-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-4-e2b',
          quant: 'q4_k_m',
          sizeBytes: 3106736256,
          params: 4647450147,
          minRamGb: 4.1,
          obsTg: 33,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/Qwen3.5-4B-GGUF',
            hfFilename: 'Qwen3.5-4B-Q4_K_M.gguf',
          },
          displayName: 'qwen3.5-4b',
          quant: 'q4_k_m',
          sizeBytes: 2740937888,
          params: 4205751296,
          minRamGb: 4.5,
          obsTg: 10.5,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'bartowski/mistralai_Ministral-3-3B-Instruct-2512-GGUF',
            hfFilename: 'mistralai_Ministral-3-3B-Instruct-2512-Q4_K_M.gguf',
          },
          displayName: 'ministral-3-3b',
          quant: 'q4_k_m',
          sizeBytes: 2146498528,
          params: 3429006336,
          minRamGb: 3.4,
          obsTg: 36,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'prism-ml/Bonsai-8B-gguf',
            hfFilename: 'Bonsai-8B-Q1_0.gguf',
          },
          displayName: 'bonsai-8b',
          quant: 'q1_0',
          sizeBytes: 1158654496,
          params: 8188548096,
          minRamGb: 2.1,
          obsTg: 20,
          badges: {
            multimodal: false,
            nativeLowBit: true,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 1.8,
          obsTg: 45.7,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
      flagship: [
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-4b-it-GGUF',
            hfFilename: 'gemma-3-4b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-4b',
          quant: 'q4_k_m',
          sizeBytes: 2489757856,
          params: 3880099328,
          minRamGb: 4.1,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-4-E4B-it-GGUF',
            hfFilename: 'gemma-4-E4B-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-4-e4b',
          quant: 'q4_k_m',
          sizeBytes: 5335289824,
          params: 7518069290,
          minRamGb: 7.3,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/gemma-4-E2B-it-GGUF',
            hfFilename: 'gemma-4-E2B-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-4-e2b',
          quant: 'q4_k_m',
          sizeBytes: 3106736256,
          params: 4647450147,
          minRamGb: 4.1,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'LiquidAI/LFM2.5-8B-A1B-GGUF',
            hfFilename: 'LFM2.5-8B-A1B-Q4_K_M.gguf',
          },
          displayName: 'lfm2.5-8b-a1b',
          quant: 'q4_k_m',
          sizeBytes: 5155564768,
          params: 8467856832,
          minRamGb: 6.2,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'unsloth/Qwen3.5-4B-GGUF',
            hfFilename: 'Qwen3.5-4B-Q4_K_M.gguf',
          },
          displayName: 'qwen3.5-4b',
          quant: 'q4_k_m',
          sizeBytes: 2740937888,
          params: 4205751296,
          minRamGb: 4.5,
          badges: {
            multimodal: true,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
        {
          key: {
            hfRepo: 'ggml-org/gemma-3-1b-it-GGUF',
            hfFilename: 'gemma-3-1b-it-Q4_K_M.gguf',
          },
          displayName: 'gemma-3-1b',
          quant: 'q4_k_m',
          sizeBytes: 806058240,
          params: 999885952,
          minRamGb: 1.8,
          obsTg: 85.6,
          badges: {
            multimodal: false,
            nativeLowBit: false,
          },
          isPrimary: true,
          source: 'device-rules',
          fitsDevice: true,
        },
      ],
    },
  },
};

export const BUNDLED_RULES_VERSION = bundledModelSuggestions.version;

export const BUNDLED_SCHEMA_VERSION = bundledModelSuggestions.schemaVersion;
